project/urls.py
from django.contrib import admin
from django.urls import path
from core import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home, name='home'),
    path('semestre/', views.semestre, name='semestre'),
    path('professores/', views.professores, name='professores'),
    path('semestre/select=<int:id>', views.select_semestre, name='select_semestre'),
    path('curso/', views.cursos_list_page, name='cursos'),
    path('dicliplinas/<int:id>/<int:id2>', views.disciplinas_list, name='disciplinas'),

    #adicionar 
     path('adicionar_semestre/', views.adicionar_semestre, name='addSemestre'),

     #usuário
     path('login/', views.login_view, name='login'),
     path('logout/', views.logout_view, name='logout'),


]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone





class Curso(models.Model):
    curso = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.curso
    
class Disciplina(models.Model):
    diciplina = models.CharField(max_length=50)
    curso = models.ForeignKey(Curso, verbose_name='curso', on_delete=models.CASCADE, null=True ,blank=True)
    periodo = models.IntegerField(blank=True, null=True)
    impar_par = models.CharField(max_length=6, blank=True)

    def save(self, *args, **kwargs):
        if self.periodo % 2 == 0:
            self.impar_par = 'par'
            print('É par')
        else:
            self.impar_par = 'impar'
            print('É impar')
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.diciplina
    
class Status(models.Model):
    status = models.CharField(max_length=16)

    def __str__(self) -> str:
        return self.status
    
class Semestre(models.Model):
    semestre = models.CharField( max_length=50)
    cursos = models.ManyToManyField(Curso, verbose_name="curso", blank=True)
    status = models.ForeignKey(Status, verbose_name='status', on_delete=models.SET_NULL, null=True, blank=True)
    date_create = models.DateTimeField(default=timezone.now)
    disciplinas = models.ManyToManyField(Disciplina, verbose_name='disciplina', blank=True)
    # par_or_impar = mode


    def __str__(self) -> str:
        return self.semestre
    
class Professor(models.Model):

    NIVELGRADUACAO = [
        ('Graduação', 'Graduação'),
        ('Mestrado', 'Mestrado'),
        ('Doutorado', 'Doutorado'),
    ]

    professor = models.OneToOneField(User, verbose_name='professor', on_delete=models.CASCADE)
    disciplinas = models.ManyToManyField(Disciplina, verbose_name='disciplinas')
    tempo_exercicio = models.DateField(blank=True, null=True)
    nivel_graduacao = models.CharField(max_length=50, choices=NIVELGRADUACAO, default='Graduação', blank=True, null=True)
    area = models.CharField(max_length=16, blank=True, null=True)

    def __str__(self) -> str:
        return self.professor.username
    
    

core/forms.py
from django.forms import ModelForm
from .models import Semestre


class SemestreForm(ModelForm):
    class Meta:
        model = Semestre
        fields = ['semestre', 'cursos','disciplinas']

core/views.py
from django.shortcuts import render, redirect
from .models import Semestre, Professor, Curso, Disciplina
from .forms import SemestreForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

@login_required(login_url="/login")
def home(request):
    return render(request, 'home.html')

@login_required(login_url="/login")
def semestre(request):
    if request.method == 'POST':
        ano_semestre = request.POST.get('ano_semestre')
        semestre = request.POST.get('semestre')
        cursos = request.POST.getlist('cursos')
        disciplinas = 'impar' if request.POST.get('disciplinas') == '1' else 'par'
        print(disciplinas)
        novo_semestre = Semestre.objects.create(semestre=f'{ano_semestre}/{semestre}')
        for curso_id in cursos:
            curso = Curso.objects.get(pk=curso_id)
            curso_disciplinas = Disciplina.objects.filter(curso=curso, impar_par=disciplinas )
            for disciplina in curso_disciplinas:
                novo_semestre.disciplinas.add(disciplina)
            print(curso_disciplinas)
            novo_semestre.cursos.add(curso)
        return redirect('semestre')
    semestre = Semestre.objects.all().order_by('-id')
    cursos = Curso.objects.all()
    disciplinas = Disciplina.objects.all().order_by('curso')
    context = {
        'semestre':semestre,
        'cursos':cursos,
        'disciplinas':disciplinas,
    }
    return render(request, 'semestre.html', context)

@login_required(login_url="/login")
def professores(request):
    if request.method == 'POST':
        print(request.POST.get('macula'))
    professor = Professor.objects.all()
    context = {
        'professor':professor,
        'form': SemestreForm()
    }
    

    return render(request, 'professores.html', context)

@login_required(login_url="/login")
def select_semestre(request, id):
    semestre = Semestre.objects.get(pk=id)
    curso = Curso.objects.all()
    context = {
        'semestre' : semestre,
        'curso': curso
    }
    return render(request, 'select_semestre.html', context)

@login_required(login_url="/login")
def cursos_list_page(request):
    curso = Curso.objects.all()
    context = {
        'curso': curso
    }
    return render(request, 'curso_list_page.html', context)

@login_required(login_url="/login")
def disciplinas_list(request, id, id2):
    print(id)
    semestre = Semestre.objects.get(pk=id)
    curso = Curso.objects.get(pk=id2)
    disciplinas = curso.disciplina_set.all()
    if request.method == 'POST':
        disciplinas_form = request.POST.getlist('select-addDisciplinas')
        print(f' disc {disciplinas_form}')
        for d in disciplinas_form:
            semestre.disciplinas.add(d)
    context = {
        'disciplinas_semestre': disciplinas.filter(semestre=semestre),
        'disciplinas_curso': Disciplina.objects.exclude(semestre=semestre).filter(curso=curso),
        'curso': curso,
        'semestre' : semestre,
        'grupo_admin': True if str(request.user.groups.all()[0]) == 'administradores' else False,
    }
    return render(request, 'disciplinas.html', context)

@login_required(login_url="/login")
def adicionar_semestre(request):
    if request.method == 'POST':
        semestre = request.POST.get('semestre')
        cursos = request.POST.getlist('curso')
        disciplinas_periodo = request.POST.get('select-disciplinas')
        print(disciplinas_periodo)
        novo_semestre = Semestre.objects.create(semestre=semestre)
        for curso in cursos:
            ...
            # curso_object = Curso.objects.get(pk=int(curso))
            # novo_semestre.cursos.add(curso_object)
          
    return redirect('semestre')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('/semestre')
        return redirect('/login')
    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('/login')

core/templates/_head.html
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'formularios.css' %}">
    <link rel="stylesheet" href="{% static 'tabelas.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>home</title>

core/templates/adicionar_semestre.html
{% extends "base.html" %}

{% block conteudo %}

<div id="formularios-addSemestre">
<form method="post" id="form-add-semestre">
    {% csrf_token %}
    <label for="input-semestre" class="label-input-text">Semestre</label>
    <input type="text" name="semestre" id="input-semestre">
    <label for="select-cursos-addSemestre" class="label-input-text">curos</label>
    <select name="curos" id="select-cursos-addSemestre" multiple>
        <option value="curso1">curo1</option>
    </select>
    <label for="select-disciplinas-addSemestre" class="label-input-text">Disciplinas</label>
    <select name="disciplinas" id="select-disciplinas-addSemestre" multiple>
        <option value="materia 1">materia 1</option>
        <option value="materia 2">materia 2</option>
    </select>
    <select name="disciplinas" id="select-disciplinas" required>
        <option value="#">impar</option>
        <option value="#">par</option>
    </select>
    <a href="#">Escolher automáticamente</a>
    <input id="button-enviar-addSemestre" type="button" value="Enviar">
</form>
</div>
{% endblock conteudo %}

core/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
   {% include "_head.html" %}
</head>
<body>

<nav>
    <div id="box-user">
        <h3><i class="bi bi-person-circle"></i> {{request.user}}</h3>
    </div>
    <ul>
        <li><a href="{% url "semestre" %}" {% if request.path_info == '/semestre/' %} class="teste" {% endif %}><i class="bi bi-calendar3"></i> Semeste </a></li>
        <li><a href="{% url "cursos" %}" {% if request.path_info == '/curso/' %} class="teste" {% endif %}><i class="bi bi-mortarboard"></i> Cursos</a></li>
        <li><a href="{% url "professores" %}" {% if request.path_info == '/professores/' %} class="teste" {% endif %}><i class="bi bi-person-vcard-fill"></i> Professores</a></li>
        {% for group in user.groups.all %}
            {% if group.name == 'administradores' %}
                <li><a href="/admin/"><i class="bi bi-person-gear"></i> Administração</a></li>
            {% endif %}
        {% endfor %}
        <li><a href="{% url "logout" %}" id="link-sair"><i class="bi bi-door-closed-fill"></i> Sair</a></li>
    </nav>
    
    <main>
        {% for group in user.groups.all %}
            {% if group.name == 'administradores' %}
                {% block opacoes %}{% endblock opacoes %}
            {% endif %}
        {% endfor %}
       
        <div id="conteiner-conteudo">
            {% block conteudo %}{% endblock conteudo %}
        </div>
</main>
<script src="{% static "scripts/script.js" %}"></script> 
</body>
</html>

core/templates/curso_list_page.html
{% extends "base.html" %}


{% block conteudo %}

<table>
    <thead>
        <tr>
            <th>Curso</th>
            <th>Disciplinas</th>
            <th>Semestre</th>
        </tr>
    </thead>
    <tbody>
       {% for i in curso %}
       <tr>
            <td>
                <a href="#">{{i}}</a>
            </td>
            <td>
              <a href="#"> disciplina(as)({{i.disciplina_set.all.count}})</a> 
            </td>
            <td>
                {% for s in i.semestre_set.all %}
                {{s}}
                {% endfor %}
            </td>
       </tr>
          
       {% endfor %}
    </tbody>
</table>

{% endblock conteudo %}

core/templates/disciplinas.html
{% extends "base.html" %}


{% block conteudo %}

<h3>{{semestre}} {{disciplinas_semestre.filter.first.curso}}</h3>
{% block opcoes %}
{% for group in user.groups.all %}
            {% if group.name == 'administradores' %}
            <div class="conteiner-menu-button">
                <a href="#" class="button-padrao color-verde" onclick="mostrar_model_addSemestre('model-addDisciplinas')"><i class="bi bi-easel2-fill"></i> adicionar</a>
            </div>
            {% endif %}
        {% endfor %}


{% endblock opcoes %}

<br>
<table>
    <thead>
        <tr>
            <th>Disciplinas</th>
            <th>Período</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        
        {% for i in disciplinas_semestre %}
        <tr>
            <td>
                <a href="#">{{i}}</a>
            </td>
            <td>
                {{i.periodo}}
            </td>
            <td>
                
                    {% if grupo_admin %}
                    <button class="color-red btn-default-acao"> 
                    Remover <i class="bi bi-x-circle"></i></i>
                    </button>
                    {% else %}
                    <button class="color-verde btn-default-acao"> 
                    Candidatar <i class="bi bi-person-fill-add"></i>
                    </button>
                    {% endif %}
                
            </td>
        </tr>
        
        {% endfor %}
        {% for group in user.groups.all %}
            {% if group.name == 'administradores' %}
            {% for i in disciplinas_curso %}
            <tr>
                 <td>
                     <p> <a href="#">{{i}}</a> (excluída)</p>
                 </td>
                 <td>
                     {{i.periodo}}
                 </td>
                 <td>
                     <button class="color-verde btn-default-acao"> Adicionar <i class="bi bi-plus-circle-fill"></i></button>
                 </td>
            </tr>
               
            {% endfor %}
            {% endif %}
        {% endfor %}
    </tbody>
</table>


{% endblock conteudo %}

core/templates/formularios/_model_base.html
<div class="janela-model" id="janela-model">
    <div class="janela-model-conteudo">
        {% block janela_model_conteudo %}{% endblock janela_model_conteudo %}
    </div>
</div>

core/templates/formularios/form_addProfessor.html
{% extends "formularios/_model_base.html" %}

{% block janela_model_conteudo %}
<form action=".">
    <div>
        <h3>Cadastrar professor</h3>
    </div>

        <label for="nome">Nome:</label>
        <input type="text" id="nome">

        <label for="sobrenome">Sobrenome:</label>
        <input type="text" id="sobrenome">

        <label for="e-mail">Email:</label>
        <input type="text" id="e-mail">

        <label for="matricula">Matrícula:</label>
        <input type="text" id="matricula">

        <label for="nivel-graduacao">Nível de graduação:</label>
        <select id="nivel-graduacao">
            <option value="#" selected disabled >-------</option>
            <option value="1">Graduação</option>
            <option value="2">Mestrado</option>
            <option value="1">Doutorado</option>
        </select>

        <label for="entrada-exercicio">Entrada em exercício:</label>
        <input type="date" name="entrada-exercicio" id="entrada-exercicio">

        <label for="are-concurso">Área que prestou o concurso:</label>
        <input type="text" id="are-concurso">

        <div class="conteiner-buttons">
            <button type="submit" class="btn-default color-verde">Salvar</button>
            <button type="button" class="btn-default color-red" onclick="fechar_model_addSemestre('janela-model')">Cancelar</button>
        </div>
    </form>

{% endblock janela_model_conteudo %}

core/templates/formularios/form_addSemestre.html
{% extends "formularios/_model_base.html" %}

{% block janela_model_conteudo %}
<form method="post">
    {% csrf_token %}
    <div>
        <h3>Cadastrar Novo Semestre</h3>
    </div>
    
        <label for="ano_semestre">Ano:</label>
        <input type="number" id="ano_semestre" name="ano_semestre" required  min="2024" >

        <label for="semestre">Semestre:</label>
        <input type="number" id="semestre" name="semestre" required min="1" max="2"  value="1">

        <label for="cursos">Cursos:</label>
        <select id="cursos" name="cursos" multiple required >
            {% for curso in cursos %}
            <option value="{{curso.id}}">{{curso}}</option>
            {% endfor %}
            
        </select>

        <label for="entrada-exercicio">Disciplinas:</label>
        <select name="disciplinas" id="disciplinas" required >
            <option selected disabled ></option>
            <option value="1">Apenas disciplinas ímpares</option>
            <option value="2">Apenas disciplinas pares</option>
        </select>
        <div class="conteiner-buttons">
            <button type="submit" class="btn-default color-verde">Salvar</button>
            <button type="button" class="btn-default color-red" onclick="fechar_model_addSemestre('janela-model')">Cancelar</button>
        </div>
    </form>

{% endblock janela_model_conteudo %}

core/templates/home.html
{% extends "base.html" %}

{% block conteudo %}

<p>
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vero commodi excepturi dicta exercitationem? Corrupti esse hic excepturi, labore rerum minima earum nostrum, iure harum doloribus ex alias aspernatur perspiciatis facere.
</p>

{% endblock conteudo %}

core/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "_head.html" %}
</head>
<body id="login-body">
    <div id="login-header">
        <h2>Sistema de Atribuição de Aulas</h2>
        <h2 id="h3-IFMT">IFMT</h2>
    </div>
    <div id="coteiner-login">
        <div id="box-login">
            <form method="post" id="form-login">
                {% csrf_token %}
       <h3><i class="bi bi-person-vcard-fill icon-login"></i>    login</h3>
       <label for="username">Usuário:</label>
    <input type="text" required class="input-login" name="username" autocomplete="off">
    <label for="password">Senha:</label>
    <input type="text" required class="input-login"name="password" autocomplete="off"> 
    <input type="submit" value="Entrar" id="button-login">
</div>
</div>
   </form>
</body>
</html>

core/templates/professores.html
{% extends "base.html" %}





{% block conteudo %}


{% block opcoes %}

{% for group in user.groups.all %}
            {% if group.name == 'administradores' %}
            <div class="conteiner-menu-button">
                <button type="button" class="btn-default color-verde" onclick="mostrar_model_addSemestre('janela-model')">Cadastrar novo Professor</button>
            </div> 
            {% endif %}
        {% endfor %}
{% endblock opcoes %}

<table>
    <thead>
        <tr>
            <th>Professor</th>
            <th>Matrícula</th>
            <th>E-mail</th>
            <th>Disciplinas</th>
        </tr>
    </thead>
    <tbody>
       {% for i in professor %}
       <tr>
            <td>
                <a href="#">{{i.professor.first_name}} {{i.professor.last_name}}</a>
            </td>
            <td>
                {{i.professor}}
            </td>
            <td>
                {{i.professor.email}}
            </td>
            <td class="table-professor-coluna-disciplinas">
                {% for d in i.disciplinas.all %}
                <span class="disciplinas-celula">{{d}}</span>
                {% endfor %}
                
            </td>
       </tr>
          
       {% endfor %}
    </tbody>
</table>

{% include "formularios/form_addProfessor.html" %}

{% endblock conteudo %}

core/templates/select_semestre.html
{% extends "base.html" %}


{% block conteudo %}

<h3> Semestre:</h3><p>{{semestre}}</p>
<hr>
<br>
<h3>Status:</h3><p>{{semestre.status}}</p>
<button>Editar</button>
<button>Exluir</button>
<br>
<br>
<hr>
<br>
<table id="semestre_curso">
    <thead>
        <tr>
            <th>Curso</th>
            <th>Disciplinas</th>
            <th>Área</th>
        </tr>
    </thead>
    <tbody>
       {% for i in semestre.cursos.all %}
       <tr>
            <td>
                <a href="{% url "disciplinas" id=semestre.id id2=i.id %}">{{i}}</a> 
            </td>
            <td>
              <a href="{% url "disciplinas" id=i.id id2=semestre.id %}">({{i.disciplina_set.all.count}})</a> 
            </td>
            <td>
                <p>#</p>
            </td>
       </tr>
          
       {% endfor %}
    </tbody>
</table>

{% endblock conteudo %}

core/templates/semestre.html
{% extends "base.html" %}

{% block conteudo %}

{% block opcoes %}

{% for group in user.groups.all %}
            {% if group.name == 'administradores' %}
            <div class="conteiner-menu-button">
                <button type="button" class="btn-default color-verde" onclick="mostrar_model_addSemestre('janela-model')">Adicionar semestre</button>
            </div> 
            {% endif %}
        {% endfor %}
{% endblock opcoes %}
<table id="semestre">
    <thead>
        <tr>
            <th>Semestre</th>
            <th>Nº Cursos</th>
            <th>Status</th>
        
        </tr>
    </thead>
    <tbody>
       {% for i in semestre %}
            <tr>
                    <td class="colum-1"><a href="{% url 'select_semestre' i.id %}"><strong>{{i}}</strong></a></td>
                    <td class="colum-2">{{i.cursos.all.count}}</td>
                    <td class="colum-3"><span id="marcador" class="color-roxo"> {{i.status}}</span></td>                  
            </tr>
       {% endfor %}
    </tbody>
</table>
    
{% include "formularios/form_addSemestre.html" %}

{% endblock conteudo %}